site_name: Wavely Docs
site_url: https://platform.wavely.io
site_description: The Wavely Platform
site_author: Wavely Team

theme:
  name: readthedocs

markdown_extensions:
  - admonition

pages:
  - Home: 'index.md'
  - General information:
      - About: 'general-information/wavely-api-docs.md'
      - Security: 'general-information/security.md'
      - Roles: 'general-information/roles.md'
      - Terminology: 'general-information/terminology.md'
      - Data Types: 'general-information/data-types.md'
      - General Errors: 'general-information/general-errors.md'
  - Web hooks:
      - Call CDR: 'webhooks/call-cdr.md'
      - Data CDR: 'webhooks/data-cdr.md' 
      - Message CDR: 'webhooks/msg-cdr.md'
      - SMS forwarding: 'webhooks/sms-forwarding.md'
      - Sim card state change: 'webhooks/sim-card-state-change.md'
  - API Specification:
      - General information: 'api/general-information.md'
      - SMS API: 'api/sms-api.md'
      - Sim cards API: 'api/simcards-api.md'
      - Call forwarding API: 'api/call-forwarding.md'