site_name: Wavely Docs
site_url: https://platform.wavely.io
site_description: The Wavely Platform
site_author: Wavely Team

theme:
  name: readthedocs

markdown_extensions:
  - toc:
      permalink: 
  - admonition
  - def_list

pages:
  - Home: 'index.md'
  - User Guide:
      - About: 'user-guide/wavely-api-docs.md'
      - Terminology: 'user-guide/terminology.md'
      - Data Types: 'user-guide/data-types.md'
      - General Errors: 'user-guide/general-errors.md'
  - API Specification:
      - SMS API: 'api/sms-api.md'
      - SimCards API: 'api/simcards-api.md'
      - Call Forwarding API: 'api/call-forwarding.md'