site_name: Wavely Docs
site_url: https://platform.wavely.io
site_description: The Wavely Platform
site_author: Wavely Team

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - json
    - java

markdown_extensions:
  - admonition

nav:
  - Home: 'index.md'
  - User Guide:
    - Terminology: 'docs/user-guide/terminology.md'
    - Data Types: 'docs/user-guide/data-types.md'
    - General Errors: 'docs/user-guide/general-errors.md'
  - API Specification:
    - SMS API: 'docs/api/sms-api.md'
    - SimCards API: 'docs/api/simcards-api.md'
    - Call Forwarding API: 'docs/api/call-forwarding.md'
