site_name: Wavely Docs
site_url: https://platform.wavely.io
site_description: The Wavely Platform
site_author: Wavely Team

theme:
  name: readthedocs

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"

pages:
  - Home: 'index.md'
  - General information:
      - About: 'general-information/wavely-api-docs.md'
      - Security: 'general-information/security.md'
      - Roles: 'general-information/roles.md'
      - Data types: 'general-information/data-types.md'
      - General errors: 'general-information/general-errors.md'
  - Web hooks:
      - About webhooks: 'webhooks/about-webhooks.md'
      - Call CDR: 'webhooks/call-cdr.md'
      - Data CDR: 'webhooks/data-cdr.md'
      - Message CDR: 'webhooks/msg-cdr.md'
      - SMS forwarding: 'webhooks/sms-forwarding.md'
      - SIM card state change: 'webhooks/sim-card-state-change.md'
  - API specification:
      - SMS: 'api/sms-api.md'
      - SIM cards: 'api/simcards-api.md'
      - Call forwarding: 'api/call-forwarding.md'
      - SIM card diagnostics: 'api/sim-card-diagnostics.md'
      - SIM card usage: 'api/sim-card-usage.md'