site_name: AxonMobile SimCard API

markdown_extensions:
  - admonition

pages:
- Home: 'user-guide/index.md'
- User Guide:
  - 'About': 'user-guide/index.md'
  - 'Terminology': 'user-guide/terminology.md'
  - 'Data Types': 'user-guide/data-types.md'
  - 'General Errors': 'user-guide/general-errors.md'
- API Specification:
  - 'SMS API': 'api/sms-api.md'
  - 'SimCards API': 'api/simcards-api.md'
