site_name: AxonMobile SimCard API

markdown_extensions:
  - admonition

pages:
- Home: 'index.md'
- User Guide: 'user-guide/index.md'
- API Specification: 'api/index.md'
    - 'SMS API': 'api/sms-api.md'
